/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Mirrors `AudioSourceTarget` in `index.d.ts`. */
export interface AudioSourceTarget {
  /** OS process id whose audio output should be captured (Windows/Linux). */
  pid?: number
  /**
   * Best-effort process/app name, used for Linux stream-matching by name
   * when a PID-level match isn't available (see PRD 12.3).
   */
  processName?: string
}
/**
 * Resolves an OS process id from an Electron `desktopCapturer` window
 * source id, formatted `"window:<HWND>:<id>"` on Windows (PRD 12.2's PID
 * resolution rule — parse the HWND out of `source.id` rather than
 * title-matching, which is fragile with duplicate window titles). Not
 * meaningful for `"screen:..."` sources, which have no associated window.
 *
 * Windows-only: this function does not exist in the compiled addon on
 * Linux/macOS at all (see `mod windows` being `cfg`-gated in `lib.rs`) —
 * callers branch on `process.platform` before ever calling it (PRD 12.7).
 */
export declare function resolvePidForWindowSourceId(sourceId: string): number | null
export declare function platformSupportsCapture(): boolean
export declare function startCapture(target: AudioSourceTarget, onFrame: (pcm: Buffer, sampleRate: number, channels: number) => void): CaptureHandle
export declare class CaptureHandle {
  get status(): string
  stop(): void
}
